### ISSUE TITLE
Ca config collections - showing as outdated reference when quick publishing

### ISSUE THREAD

**Issue by srikanthgurram-17** [wcm-io/io.wcm.caconfig.editor#48]
Hi @stefanseifert GoodDay

We are using 1.16.6 version of ca config editor where we have multiple ca configurations where each config has multiple fields for eg: background color config has color name, color value, checkbox field.

Steps to reproduce the problem: 

1. Open a existing  background color configuration (this config already exists for 10 different colors)
2. Edit one config inside the above background color configuration 
3. save and try quick publish
4. page redirects to another screen where we see list of outdated configs
Expected result: I should see only the config that I edited in the outdated config list. and I should be easily able to publish single config.

Actual result:  Instead I see all the 10 background color configs listed as outdated. this is a problem if you have more number configs for eg: around 200 items . this would take lot of time to quick publish and resulting to 503 sometimes

Thanks in advance!

**Comment by stefanseifert** [comment]
i assume you are using the wcm.io AEM Page persistence strategy from https://wcm.io/caconfig/extensions which stores each list item in a separate page, which should theoretically only show modified/new list items when publishing again.

actually, the problem happens as you are describing: if only one list item is updated, all list items and the list page itself is showed as outdated. the reason is, that on each save all list items are re-saved, and the `jcr:lastModified` property of all items and the list itself are updated as well, so all are offered for re-publication.

the persistence strategy should be adapted in a way, that `jcr:lastModified` is only updated when actual changes are done when saving the list with it's items. i will have a look on it, but cannot promise a date for a fix yet (feel free to open a PR to get it done faster).

**Comment by srikanthgurram-17** [comment]
I will come up with a PR for this!

**Comment by srikanthgurram-17** [comment]
[https://github.com/wcm-io/io.wcm.caconfig.extensions/pull/8](url)

**Comment by stefanseifert** [comment]
closing this one as the actual implementation is taking place in a different module https://github.com/wcm-io/io.wcm.caconfig.extensions

follow-up in PR https://github.com/wcm-io/io.wcm.caconfig.extensions/pull/8
